### ISSUE TITLE
Description Mentioned in Table 6 Not Found in Dataset

### ISSUE THREAD

**Issue by Maxwang1127** [Robertwyq/Drivingdojo#1]
Hi,
Great work! I noticed the description mentioned in Table 6: "The explanation of the information in dataset_info.json," but I couldn't find it in the downloaded dataset. Will this be released later?
Thanks!

**Comment by Maxwang1127** [comment]
![lQLPKH5kZo57gw3NAVfNBIGw2ZdmM35_K3wHBxbLYA3bAA_1153_343](https://github.com/user-attachments/assets/480760bb-a912-4548-9bdc-18bbbad3170f)

**Comment by Robertwyq** [comment]
@Maxwang1127 Hi, the short descriptions in meta.json provide concise information, such as hard braking triggered by dynamic objects or suddenly appearing pedestrians.

**Comment by Maxwang1127** [comment]
> @Maxwang1127 Hi, the short descriptions in meta.json provide concise information, such as hard braking triggered by dynamic objects or suddenly appearing pedestrians.

Well received, thanks for the reply!
