### ISSUE TITLE
Dojo dataset subsets 

### ISSUE THREAD

**Issue by mingzhuzhang1** [Robertwyq/Drivingdojo#2]
Hello, your work is incredibly valuable. I have a question regarding the Dojo dataset, which is divided into three subsets in the paper. Due to limited storage space, I was wondering if it’s possible to obtain just one of these subsets, specifically DrivingDojo-Open subset. I would greatly appreciate any guidance you could provide and look forward to your response!

**Comment by Robertwyq** [comment]
Hi @mingzhuzhang1 , sorry the current storage does not allow for extracting only a subset, as the videos are uploaded in a mixed format and all videos are intertwined.
