### ISSUE TITLE
Dojo training code

### ISSUE THREAD

**Issue by Hongbo123467** [Robertwyq/Drivingdojo#3]
It seems that the training code only supports nuscenes/waymo dataset. Do you have any plans to release the training code for Driving Dojo dataset?

**Comment by Robertwyq** [comment]
Hi @Hongbo123467 , we just uploaded the training script for the dojo, it is similar to waymo/nuscenes, and the action training code will be released later.

**Comment by Hongbo123467** [comment]
Thank you for your response！I would also like to ask if the Driving Dojo dataset includes only forward-view camera images from vehicles or if it also contains surround-view images.

**Comment by Robertwyq** [comment]
Hi @Hongbo123467 , currently it only includes front-view camera images.
