### ISSUE TITLE
videos_35.tar.gz errors

### ISSUE THREAD

**Issue by LandSeaMelody** [Robertwyq/Drivingdojo#4]
videos_35.tar.gz keeps reporting errors when decompressing

**Comment by Robertwyq** [comment]
@Zhao-ZD Indeed, there seems to have been an issue during compression process. Thank you for pointing this out. We will upload a new tar.gz as soon as possible.

**Comment by Robertwyq** [comment]
@Zhao-ZD , We have re-uploaded the videos_35 file, and it is now available at the following location: https://huggingface.co/datasets/Yuqi1997/DrivingDojo-Extra5.
