### ISSUE TITLE
There is no tokenizer file in the pre-trained model

### ISSUE THREAD

**Issue by suannairen** [Robertwyq/Drivingdojo#6]
There is no tokenizer file in the pre-trained model, but the tokenizer is loaded in the train_video_svd_fsdp.py file
![image](https://github.com/user-attachments/assets/730a44f6-ae5d-4b29-b1a3-d39ede4277fb)
![image](https://github.com/user-attachments/assets/63c9ee55-40ec-4351-93e3-32e7685a6d1e)

**Comment by Robertwyq** [comment]
@suannairen The tokenizer is actually not use in the code, you can give it to None, or use the path from the original SVD checkpoint, https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt.
